---
- name: Testing andrewrothstein.python
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'python3 --version'
      ansible.builtin.command: python3 --version
      changed_when: false
      register: python_test_output
    - name: Output from 'python3 --version'
      ansible.builtin.debug:
        msg: '{{ python_test_output.stdout }}'
