---
- name: (Ubuntu) add deadsnake ppa
  apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'
  register: deadsnake_ppa_added

- name: (Ubuntu) update cache...
  when: deadsnake_ppa_added|changed
  apt: update_cache=yes

- name: (Ubuntu) python packages...
  when: deadsnake_ppa_added|changed
  shell: apt-get upgrade -y python python-dev python-pip

